"""
Migration khởi tạo bảng `Users` cho app authentication.

File này chứa định nghĩa schema của user table dùng cho hệ thống UITie:
- login/bảo mật với email/password
- phân quyền theo role
- quản lý trạng thái account (Active/Locked/Inactive)
- thông tin sinh viên như mssv, faculty, class_name, academic_year

Tại sao giữ `managed=False`:
- Bảng đã tồn tại trong database legacy, Django chỉ map schema chứ không
  tự động tạo/xóa bảng trong migration runtime.
"""

# Generated by Django 6.0.5 on 2026-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, unique=True)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('full_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('mssv', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('role', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('status_reason', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('faculty', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('academic_year', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('remember_token', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
